language: ruby

sudo: required

matrix:
  include:
  - os: osx
    rvm: 2.3.0
    osx_image: xcode8.2
  - os: osx
    rvm: 2.3.0
    osx_image: xcode7.3

before_install:
  - sudo dscl . -passwd /Users/travis travis

install:
  - curl -L https://www.chef.io/chef/install.sh | sudo bash -s -- -P chefdk
  - chef exec bundle update

script:
  - chef exec bundle exec rake
  - KITCHEN_YAML=.kitchen.localhost.yml chef exec bundle exec kitchen test
